# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Post-merge tasks
on:
  push:
    branches: [ master ]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
        id: nvm
      - name: Use Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'
      - name: Run merge tasks
        run: |
          npm ci
#      - name: Publish NPM package
#        uses: JS-DevTools/npm-publish@v3
#        with:
#          token: ${{ secrets.NPM_TOKEN }}
